language: java
sudo: false
script: mvn clean verify
jdk:
  - oraclejdk8
  
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MHNlcGhlY3VyZSUzQW1hdHJpeC5jbGVyaXN5LmluZm8vJTIxQ2xFdmd1VUJGYVNwTElGTkVFJTNBcmlnZWwuZ3VyZ3kubWUlM0E4NDQ4"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never